### ISSUE TITLE
error handle

### ISSUE THREAD

**Issue by yanlongLv** [Go-000/Go-000#18]
#学号:G20200607010931
#姓名: jensen
#班级:6班
#作业&总结链接: https://github.com/yanlongLv/Go-000/tree/main/Week02/jike

**Comment by yingnan1314** [comment]
> #学号:G20200607010931
> #姓名: jensen
> #班级:6班
> #作业&总结链接: https://github.com/yanlongLv/Go-000/tree/main/Week02/jike

发错地方了
